import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Unity, useUnityContext } from "react-unity-webgl";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { unityProvider } = useUnityContext({
    loaderUrl: "unity/Build/WEBGL.loader.js",
    dataUrl: "unity/Build/WEBGL.data",
    frameworkUrl: "unity/Build/WEBGL.framework.js",
    codeUrl: "unity/Build/WEBGL.wasm",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: "100vw", height: "100vh" }}>
        <Unity
          unityProvider={unityProvider}
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            zIndex: 1,
          }}
        />
      </div>
    </>
  );
}
