import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Unity, useUnityContext } from "react-unity-webgl";
import { AppLoading } from "@/components/AppLoading";
import DraggableCircle from "@/components/DraggableCircle";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { unityProvider, loadingProgression, isLoaded } = useUnityContext({
    loaderUrl: "unity/240704/Build/240704.loader.js",
    dataUrl: "unity/240704/Build/240704.data",
    frameworkUrl: "unity/240704/Build/240704.framework.js",
    codeUrl: "unity/240704/Build/240704.wasm",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: "100vw", height: "100vh" }}>
        <AppLoading loadingProgression={loadingProgression} />
        <Unity
          unityProvider={unityProvider}
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            zIndex: 1,
          }}
        />
        <div style={{ height: "100vh", width: "100vw", position: "relative" }}>
          <DraggableCircle />
        </div>
      </div>
    </>
  );
}
